include(GNUInstallDirs)

install(TARGETS proto graph markov service textchain
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

install(TARGETS ${PROJECT_NAME}
  RUNTIME_DEPENDENCY_SET ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR}
)

install(RUNTIME_DEPENDENCY_SET ${PROJECT_NAME}
  DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

include(CPack)
