include(GNUInstallDirs)

install(TARGETS proto graph markov textchain
  LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

if (KUSAI_BUILD_SERVICE)
    install(TARGETS service
            LIBRARY DESTINATION ${CMAKE_INSTALL_LIBDIR}
    )
endif ()

if (KUSAI_BUILD_APP)
    install(TARGETS ${PROJECT_NAME}
      RUNTIME_DEPENDENCY_SET ${PROJECT_NAME} DESTINATION ${CMAKE_INSTALL_BINDIR}
    )
endif ()

install(RUNTIME_DEPENDENCY_SET ${PROJECT_NAME}
  DESTINATION ${CMAKE_INSTALL_LIBDIR}
)

include(CPack)
