# Copyright (c) Kasefuchs
# SPDX-License-Identifier: MIT

---
version: 3

tasks:
  add-license-headers:
    cmd: go run github.com/hashicorp/copywrite headers

  validate-license:
    cmd: go run github.com/hashicorp/copywrite license
