when:
  - event: tag
steps:
  - name: build
    image: ghcr.io/kasefuchs/containers/cmake:4.3.1
    commands:
      # Install dependencies
      - apt-get update --assume-yes
      - apt-get install --assume-yes libabsl-dev libcli11-dev libxxhash-dev nlohmann-json3-dev
      # Build doc
      - cmake -B cmake-build-doc -DCMAKE_BUILD_TYPE=Release -DKUSAI_BUILD_DOC=ON
      - cmake --build cmake-build-doc --config Release --target doc
  - name: publish
    image: jfxs/wrangler:4.73
    environment:
      CLOUDFLARE_ACCOUNT_ID:
        from_secret: CLOUDFLARE_PAGES_ACCOUNT_ID
      CLOUDFLARE_API_TOKEN:
        from_secret: CLOUDFLARE_PAGES_API_TOKEN
    commands:
      - wrangler pages deploy cmake-build-doc/doc/html --project-name "$${CI_REPO_NAME}"
