---
when:
  - event: tag

matrix:
  LINKAGE:
    - dynamic
    - static

steps:
  - name: build
    image: ghcr.io/kasefuchs/vcpkg
    environment:
      VCPKG_OVERLAY_PORTS: /tmp/overlay-ports
    commands: # language="sh"
      # Install dependencies
      - apt-get update --assume-yes
      - apt-get install --assume-yes libabsl-dev libcli11-dev libpugixml-dev
      - tools/vcpkg/gen-overlay.sh abseil cli11 pugixml

      # Compile app
      - >-
        cmake -G Ninja -B cmake-build-${LINKAGE}
        -DCMAKE_TOOLCHAIN_FILE=$${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
        -DVCPKG_TARGET_TRIPLET=$([ "${LINKAGE}" = "static" ] && echo x64-linux || echo x64-linux-dynamic)
        -DBUILD_SHARED_LIBS=$([ "${LINKAGE}" = "static" ] && echo OFF || echo ON)
        -DCMAKE_BUILD_TYPE=Release
        -DKUSAI_BUILD_APP=ON
      - cmake --build cmake-build-${LINKAGE} --config Release

      # Package build
      - cd cmake-build-${LINKAGE}
      - cpack

  - name: publish
    image: woodpeckerci/plugin-release
    settings:
      title: ${CI_COMMIT_TAG}
      files:
        - cmake-build-*/dist/*
      api_key:
        from_secret: CODEBERG_RELEASE_API_TOKEN
