set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

if (APPLE)
  set(CMAKE_INSTALL_RPATH "@loader_path/../lib")
elseif (UNIX)
  set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib")
endif ()

if (BUILD_SHARED_LIBS)
  set(KUSAI_LINKAGE "shared")
else()
  set(KUSAI_LINKAGE "static")
endif()

set(CPACK_GENERATOR "TGZ;ZIP;DEB")
set(CPACK_OUTPUT_FILE_PREFIX "${CMAKE_BINARY_DIR}/dist")
set(CPACK_PACKAGE_FILE_NAME "${PROJECT_NAME}-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}-${KUSAI_LINKAGE}")
set(CPACK_PACKAGE_CONTACT "kasefuchs@protonmail.com")
set(CPACK_PACKAGE_LICENSE "MIT")
set(CPACK_DEBIAN_PACKAGE_SHLIBDEPS ON)

set(DOXYGEN_USE_MDFILE_AS_MAINPAGE "${CMAKE_SOURCE_DIR}/README.md")
set(DOXYGEN_STRIP_FROM_PATH
  "${CMAKE_SOURCE_DIR}/include"
  "${CMAKE_SOURCE_DIR}/src"
)

option(KUSAI_INSTALL "Enable install" OFF)
option(KUSAI_BUILD_APP "Build CLI app" OFF)
option(KUSAI_BUILD_DOC "Build documentation" OFF)
option(KUSAI_BUILD_PYTHON "Build Python bindings" OFF)
option(KUSAI_BUILD_WASM "Build WASM bindings" OFF)
